# Generated by Django 4.0.2 on 2022-02-07 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dolznost',
            options={'verbose_name': 'Должности', 'verbose_name_plural': '01 Должности'},
        ),
        migrations.AlterModelOptions(
            name='klientfizlizo',
            options={'verbose_name': 'Клиенты физ лица', 'verbose_name_plural': '07 Клиенты физ лица'},
        ),
        migrations.AlterModelOptions(
            name='klienturlizo',
            options={'verbose_name': 'Клиенты юр лица', 'verbose_name_plural': '08 Клиенты юр лица'},
        ),
        migrations.AlterModelOptions(
            name='otdel',
            options={'verbose_name': 'Отделы', 'verbose_name_plural': '02 Отделы'},
        ),
        migrations.AlterModelOptions(
            name='roddeiatelnosti',
            options={'verbose_name': 'Род деятельности', 'verbose_name_plural': '06 Род деятельности'},
        ),
        migrations.AlterModelOptions(
            name='semeinoepolozenie',
            options={'verbose_name': 'Семейные положения', 'verbose_name_plural': '04 Семейные положения'},
        ),
        migrations.AlterModelOptions(
            name='sotrudnic',
            options={'verbose_name': 'Сотрудники', 'verbose_name_plural': '03 Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='tipliza',
            options={'verbose_name': 'Типы юр лица', 'verbose_name_plural': '05 Типы юр лица'},
        ),
        migrations.AlterField(
            model_name='klient',
            name='rod_deiatelnosti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bank.roddeiatelnosti', verbose_name='Род деятельности'),
        ),
        migrations.AlterField(
            model_name='sotrudnic',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин'),
        ),
    ]
