# Generated by Django 4.0.2 on 2022-02-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_dolznost_options_alter_klientfizlizo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='istoriaizmeneniaklienta',
            options={'verbose_name': 'Истории изменений', 'verbose_name_plural': '10 Истории изменений'},
        ),
        migrations.AlterModelOptions(
            name='tipizmeneniaistorii',
            options={'verbose_name': 'Типы изменения историй клиентов', 'verbose_name_plural': '09 Типы изменения историй клиентов'},
        ),
        migrations.AlterField(
            model_name='istoriaizmeneniaklienta',
            name='danie_stali',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные стали'),
        ),
        migrations.AlterField(
            model_name='istoriaizmeneniaklienta',
            name='data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения'),
        ),
    ]
