# Generated by Django 4.0.2 on 2022-02-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_istoriaizmeneniaklienta_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dvizenieposhetu',
            options={'verbose_name': 'Движения по счётам', 'verbose_name_plural': '16 Движения по счётам'},
        ),
        migrations.AlterModelOptions(
            name='graficviplatikredita',
            options={'verbose_name': 'Графики выплат кредитов', 'verbose_name_plural': '20 Графики выплат кредитов'},
        ),
        migrations.AlterModelOptions(
            name='kartochka',
            options={'verbose_name': 'Карточки', 'verbose_name_plural': '18 Карточки'},
        ),
        migrations.AlterModelOptions(
            name='kredit',
            options={'verbose_name': 'Кредитования', 'verbose_name_plural': '19 Кредитования'},
        ),
        migrations.AlterModelOptions(
            name='lichniedocumentklienta',
            options={'verbose_name': 'Личные документы клиентов', 'verbose_name_plural': '12 Личные документы клиентов'},
        ),
        migrations.AlterModelOptions(
            name='shet',
            options={'verbose_name': 'Счета', 'verbose_name_plural': '14 Счета'},
        ),
        migrations.AlterModelOptions(
            name='tipdocumentov',
            options={'verbose_name': 'Типы документов', 'verbose_name_plural': '11 Типы документов'},
        ),
        migrations.AlterModelOptions(
            name='tipdvizenieposhetu',
            options={'verbose_name': 'Типы движения по счетам', 'verbose_name_plural': '15 Типы движения по счетам'},
        ),
        migrations.AlterModelOptions(
            name='tipplateznoisistemi',
            options={'verbose_name': 'Типы платёжной системы', 'verbose_name_plural': '17 Типы платёжной системы'},
        ),
        migrations.AlterModelOptions(
            name='tipsheta',
            options={'verbose_name': 'Типы счетов', 'verbose_name_plural': '13 Типы счетов'},
        ),
        migrations.AlterField(
            model_name='shet',
            name='nomer_sheta',
            field=models.CharField(db_index=True, default=1, max_length=255, unique=True, verbose_name='Номер счёта'),
            preserve_default=False,
        ),
    ]
