# Generated by Django 4.0.2 on 2022-02-07 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_dvizenieposhetu_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graficviplatikredita',
            name='kredit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank.kredit', verbose_name='Кредит'),
        ),
        migrations.AlterField(
            model_name='kredit',
            name='sotrudnoc_vidavchi_kredit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.sotrudnic', verbose_name='Сотрудник который выдал кредит'),
        ),
    ]
