# Generated by Django 3.2.13 on 2022-06-27 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Авторы',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Книги',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Город',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название')),
                ('address', models.CharField(db_index=True, max_length=255, verbose_name='Адресс')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Контактный телефон')),
            ],
            options={
                'verbose_name': 'Покупатели',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата доставки')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibleoteka.city', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставка',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Имя')),
                ('address', models.CharField(db_index=True, max_length=255, verbose_name='Адресс')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Контактный телефон')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Работники',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Город',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата заказа')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibleoteka.customer', verbose_name='Покупатель')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibleoteka.employees', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказ',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Имя')),
                ('address', models.CharField(db_index=True, max_length=255, verbose_name='Адресс')),
                ('inn', models.CharField(db_index=True, max_length=255, verbose_name='ИНН')),
                ('fax', models.CharField(db_index=True, max_length=255, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Поставщики',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Treaty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата договора')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibleoteka.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договор',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibleoteka.book', verbose_name='Книга')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibleoteka.delivery', verbose_name='Доставка')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склад',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='Цена')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibleoteka.book', verbose_name='Книга')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibleoteka.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупка',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='Количество')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibleoteka.book', verbose_name='Книга')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibleoteka.order', verbose_name='Заказ')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibleoteka.purchase', verbose_name='Покупка')),
            ],
            options={
                'verbose_name': 'Детали_заказа',
                'verbose_name_plural': 'Детали_заказа',
            },
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vozvrata', models.DateField(blank=True, null=True, verbose_name='Дата заказа')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibleoteka.book', verbose_name='Книга')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibleoteka.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ_книг',
                'verbose_name_plural': 'Заказ_книг',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='treaty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibleoteka.treaty', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='suppliers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibleoteka.suppliers', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibleoteka.genre', verbose_name='Жанр'),
        ),
        migrations.CreateModel(
            name='AuthorBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibleoteka.author', verbose_name='Автор')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibleoteka.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Авторы',
                'verbose_name_plural': 'Авторы',
            },
        ),
    ]
